/* ═══════════════════════════════════════════════
   PADSCHA – Product Data
   Edit products here to update the catalog.
   ═══════════════════════════════════════════════ */

window.PADSCHA_PRODUCTS = [
  {
    sku: "PDS-PAD-001",
    slug: "royal-lotus-padparadscha-sapphire",
    name: "Royal Lotus Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ รอยัลโลตัส",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 10000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Lotus pink-orange padparadscha tone",
    colorTh: "โทนพัดพารัดชาชมพูอมส้มแบบกลีบบัว",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Available",
    shortDescription:
      "Certificate verified · To be confirmed from lab report · Lotus pink-orange padparadscha tone",
    shortDescriptionTh:
      "ยืนยันด้วยใบเซอร์ · ยืนยันจากรายงานห้องแล็บ · โทนพัดพารัดชาชมพูอมส้มแบบกลีบบัว",
    shortDescriptionEn:
      "A premium padparadscha listing for buyers who want a lotus pink-orange tone with video and certificate proof before viewing.",
    story:
      "Padscha เน้นคัดเฉพาะพัดพารัดชาที่มีหลักฐานชัดเจน สีต้องดูได้จริงในหลายสภาพแสง และข้อมูล treatment ต้องเปิดเผยก่อนตัดสินใจ",
    storyEn:
      "Padscha focuses on padparadscha sapphires with clear proof, color that can be reviewed in multiple lighting conditions, and treatment disclosure before every decision.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#ffb199",
  },
  {
    sku: "PDS-PAD-002",
    slug: "sunrise-padparadscha-sapphire",
    name: "Sunrise Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ ซันไรส์",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 10000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Soft peach-pink with warm orange glow",
    colorTh: "พีชอมชมพูพร้อมประกายส้มอุ่น",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Reserved",
    shortDescription:
      "Certificate verified · To be confirmed from lab report · Soft peach-pink with warm orange glow",
    shortDescriptionTh:
      "ยืนยันด้วยใบเซอร์ · ยืนยันจากรายงานห้องแล็บ · พีชอมชมพูพร้อมประกายส้มอุ่น",
    shortDescriptionEn:
      "Selected for buyers who prefer a soft, bright padparadscha tone that feels refined rather than overly saturated.",
    story:
      "สถานะการจองจะอัปเดตบนเว็บเพื่อให้ทีมขายตอบลูกค้าได้ตรงกัน และลดการสอบถามซ้ำในรายการที่ถูกจองแล้ว",
    storyEn:
      "Reservation status is shown clearly so the sales team can answer consistently and reduce duplicate inquiries for stones already under hold.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#ffad8f",
  },
  {
    sku: "PDS-PAD-003",
    slug: "collector-padparadscha-sapphire",
    name: "Collector Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ เกรดสะสม",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 10000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Balanced pink-orange collector tone",
    colorTh: "ชมพูส้มบาลานซ์สำหรับสายสะสม",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Available",
    shortDescription:
      "Certificate verified · To be confirmed from lab report · Balanced pink-orange collector tone",
    shortDescriptionTh:
      "ยืนยันด้วยใบเซอร์ · ยืนยันจากรายงานห้องแล็บ · ชมพูส้มบาลานซ์สำหรับสายสะสม",
    shortDescriptionEn:
      "Ideal for clients who choose the center stone first, then decide on the setting later.",
    story:
      "เว็บไซต์นี้จึงไม่มีตะกร้าสินค้า แต่พาลูกค้าไปขอหลักฐานของ SKU นั้นผ่าน LINE เพื่อให้ทีม Padscha ดูแลเป็นรายเคส",
    storyEn:
      "This catalog intentionally has no cart; each product leads to a SKU-specific LINE inquiry so the Padscha team can handle each buyer personally.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#fb8f85",
  },
  {
    sku: "PDS-PAD-005",
    slug: "blossom-padparadscha-sapphire",
    name: "Blossom Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ บลอสซั่ม",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 10000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Delicate cherry blossom padparadscha tone",
    colorTh: "โทนพัดพารัดชาชมพูอ่อนดั่งดอกซากุระ",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Available",
    shortDescription: "Certificate verified · Cherry blossom padparadscha tone · Premium grade",
    shortDescriptionTh: "ยืนยันด้วยใบเซอร์ · โทนชมพูอ่อนดั่งดอกซากุระ · เกรดพรีเมียม",
    shortDescriptionEn: "A delicate cherry blossom padparadscha tone for buyers who prefer lighter, more refined hues.",
    story: "โทนสีชมพูอ่อนบอบบางของ Blossom ให้ความรู้สึกสงบและซาบซึ้ง เหมาะสำหรับผู้ที่ต้องการพัดพารัดชาในแนวสีอ่อนและประณีต",
    storyEn: "The delicate light pink of Blossom brings a calm, refined feeling — ideal for buyers who prefer a softer padparadscha hue.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#ffcbb8",
  },
  {
    sku: "PDS-PAD-006",
    slug: "golden-hour-padparadscha-sapphire",
    name: "Golden Hour Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ โกลเด้นอาวร์",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 12000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Warm golden-orange padparadscha tone",
    colorTh: "โทนพัดพารัดชาส้มทองอุ่น",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Reserved",
    shortDescription: "Certificate verified · Warm golden-orange tone · Inquiry open",
    shortDescriptionTh: "ยืนยันด้วยใบเซอร์ · โทนส้มทองอุ่น · เปิดรับสอบถาม",
    shortDescriptionEn: "A warm golden-orange padparadscha for buyers drawn to the sunset hue range of this rare sapphire variety.",
    story: "โทนส้มทองของ Golden Hour ให้ความอบอุ่นและเปล่งประกายในแบบที่หาได้ยากในกลุ่มพัดพารัดชา",
    storyEn: "The warm golden-orange of Golden Hour has a rare radiance that stands out even in the padparadscha category.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#ffb07c",
  },
  {
    sku: "PDS-PAD-007",
    slug: "silk-rose-padparadscha-sapphire",
    name: "Silk Rose Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ ซิลค์โรส",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 10000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Silky rose-pink with soft orange edge",
    colorTh: "ชมพูกุหลาบนุ่มพร้อมขอบส้มอ่อน",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Available",
    shortDescription: "Certificate verified · Silky rose-pink with soft orange edge",
    shortDescriptionTh: "ยืนยันด้วยใบเซอร์ · ชมพูกุหลาบนุ่มพร้อมขอบส้มอ่อน",
    shortDescriptionEn: "A silky rose-pink padparadscha with a soft orange edge — a classic combination for collectors.",
    story: "Silk Rose มีสีชมพูกุหลาบที่นุ่มนวล เส้นสีส้มอ่อนที่ขอบทำให้ดูมีมิติและเป็นเอกลักษณ์",
    storyEn: "Silk Rose features a soft rose-pink body with a gentle orange edge that gives it dimension and a classic padparadscha character.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#ffb3a7",
  },
  {
    sku: "PDS-PAD-008",
    slug: "flame-padparadscha-sapphire",
    name: "Flame Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ เฟลม",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 15000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Deep saturated orange-pink flame tone",
    colorTh: "ส้มชมพูอิ่มสีสดแบบเปลวไฟ",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Available",
    shortDescription: "Certificate verified · Deep saturated orange-pink flame tone",
    shortDescriptionTh: "ยืนยันด้วยใบเซอร์ · ส้มชมพูอิ่มสีสดแบบเปลวไฟ",
    shortDescriptionEn: "A deeply saturated orange-pink flame tone for collectors who want the boldest padparadscha expression.",
    story: "Flame คือพัดพารัดชาที่มีความอิ่มสีสูง ประกายแรงและโดดเด่นในทุกสภาพแสง เหมาะสำหรับนักสะสมที่ต้องการพลอยที่แสดงตัวตนออกมาอย่างเต็มที่",
    storyEn: "Flame is a deeply saturated padparadscha that commands attention in any light — for collectors who want the boldest color expression.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#ff7e5f",
  },
  {
    sku: "PDS-PAD-009",
    slug: "dawn-padparadscha-sapphire",
    name: "Dawn Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ ดอน",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 10000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Soft dawn light pink-peach tone",
    colorTh: "ชมพูพีชอ่อนดั่งแสงรุ่งอรุณ",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Available",
    shortDescription: "Certificate verified · Soft dawn light pink-peach tone",
    shortDescriptionTh: "ยืนยันด้วยใบเซอร์ · ชมพูพีชอ่อนดั่งแสงรุ่งอรุณ",
    shortDescriptionEn: "A gentle dawn-inspired pink-peach that suits buyers looking for an elegant, understated padparadscha.",
    story: "Dawn มีสีชมพูพีชนุ่มที่ชวนให้นึกถึงแสงแรกของเช้า เหมาะสำหรับผู้ที่ต้องการความงามที่สุขุมและประณีต",
    storyEn: "Dawn has a gentle pink-peach that evokes the first light of morning — suited to buyers who appreciate quiet elegance.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#ffcba4",
  },
  {
    sku: "PDS-PAD-010",
    slug: "coral-padparadscha-sapphire",
    name: "Coral Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ คอรัล",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: 13000,
    carat: "Certificate verified",
    size: "Details on request",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Vivid coral padparadscha tone",
    colorTh: "โทนพัดพารัดชาปะการังสดใส",
    origin: "To be confirmed from lab report",
    originTh: "ยืนยันจากใบเซอร์ของเม็ดจริง",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์ของเม็ดจริง",
    certificate: "International lab certificate available",
    certificateTh: "ใบเซอร์จากสถาบันระดับสากล",
    status: "Reserved",
    shortDescription: "Certificate verified · Vivid coral padparadscha tone · Highly sought",
    shortDescriptionTh: "ยืนยันด้วยใบเซอร์ · โทนปะการังสดใส · เป็นที่ต้องการสูง",
    shortDescriptionEn: "A vivid coral padparadscha tone that sits at the ideal intersection of pink and orange — one of the most sought-after ranges.",
    story: "Coral อยู่ในโซนสีที่นักสะสมต้องการมากที่สุด คือจุดที่ชมพูและส้มมาบรรจบกันอย่างสมดุลสมบูรณ์แบบ",
    storyEn: "Coral sits in the most sought-after padparadscha zone — where pink and orange meet in perfect balance.",
    image: "padparadscha_gem.png",
    tags: ["3-light video", "Certificate", "Treatment disclosed"],
    accent: "#ff8c69",
  },
  {
    sku: "PDS-PAD-004",
    slug: "archive-padparadscha-sapphire",
    name: "Archive Padparadscha Sapphire",
    thaiName: "พัดพารัดชาแซฟไฟร์ คลังผลงาน",
    category: "Padparadscha Sapphire",
    categoryTh: "PADPARADSCHA SAPPHIRE",
    price: null,
    carat: "Sold reference",
    size: "Archive record",
    cut: "Premium faceted stone",
    cutTh: "พลอยเจียระไนเกรดพรีเมียม",
    color: "Past Padscha padparadscha selection",
    colorTh: "ตัวอย่างโทนพัดพารัดชาที่เคยคัดโดย Padscha",
    origin: "Archive",
    originTh: "คลังผลงาน",
    treatment: "Disclosed before sale",
    treatmentTh: "เปิดเผยก่อนการขายแล้ว",
    certificate: "Certificate handled with buyer record",
    certificateTh: "ใบเซอร์จัดเก็บตามข้อมูลลูกค้าที่ซื้อแล้ว",
    status: "Sold",
    shortDescription:
      "Sold archive — used to showcase Padscha's color direction and selection standard.",
    shortDescriptionTh:
      "คลังผลงานที่ขายแล้ว — แสดงทิศทางสีและมาตรฐานการคัดของ Padscha",
    shortDescriptionEn:
      "A sold archive item used to show Padscha's color direction and selection standard.",
    story:
      "คลังผลงานช่วยสร้างความมั่นใจโดยไม่ทำให้ลูกค้าสับสนกับสินค้าพร้อมจองในปัจจุบัน",
    storyEn:
      "Archive listings build trust without confusing buyers about what is currently available.",
    image: "padparadscha_gem.png",
    tags: ["Archive", "Reference"],
    accent: "#d8897e",
  },
  {
    sku: "PDS-JWL-001",
    slug: "padparadscha-diamond-halo-ring",
    name: "Padparadscha Diamond Halo Ring",
    thaiName: "แหวนพัดพารัดชาล้อมเพชร",
    category: "Jewelry",
    categoryTh: "เครื่องประดับ",
    price: null,
    carat: "สอบถามราคา",
    size: "สั่งทำตามขนาด",
    cut: "Oval",
    cutTh: "โอวัล",
    color: "Padparadscha pink-orange",
    colorTh: "พัดพารัดชาชมพูอมส้ม",
    origin: "To be confirmed",
    originTh: "ยืนยันตามใบเซอร์",
    treatment: "Disclosed per certificate",
    treatmentTh: "เปิดเผยตามใบเซอร์",
    certificate: "Available on request",
    certificateTh: "มีใบเซอร์ตามคำขอ",
    status: "Available",
    shortDescription: "Padparadscha sapphire with diamond halo · White gold setting · Made to order",
    shortDescriptionTh: "พัดพารัดชาล้อมเพชร · ตัวเรือนไวท์โกลด์ · สั่งทำพิเศษ",
    story: "แหวนพัดพารัดชาล้อมเพชรตัวเรือนไวท์โกลด์ สั่งทำพิเศษตามขนาดและความต้องการ ติดต่อทีมงานเพื่อรับคำปรึกษาและออกแบบชิ้นงานของคุณ",
    storyEn: "A padparadscha sapphire set in a diamond halo white gold ring. Each piece is made to order — contact our team for a personal consultation and custom design.",
    image: "{C24AC94E-715B-4D34-A935-5F7C9F3877B5}.png",
    tags: ["Made to order", "Diamond halo", "White gold"],
    accent: "#ffb199",
  },
];

window.PADSCHA_CONTACT = {
  line: "https://line.me/R/ti/p/@051xmmtu?ts=01042156&oat_content=url",
  lineOaId: "@051xmmtu",
  lineLabel: "@051xmmtu",
  instagram: "https://www.instagram.com/pads.cha",
  instagramLabel: "@pads.cha",
  facebook: "https://web.facebook.com/Padscha",
  facebookLabel: "Padscha Bangkok",
  tiktok: "https://www.tiktok.com/@padscha4?_t=ZS-8smlRXFZHr0&_r=1&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGneY8DmpNWVl7GhoOjzaTGlrlGQ0D3C2o6Ym-Aj4VP6UbSwBuxxRYuSxlApMY_aem_6AZFoaeNpBKl0bq2kKig7Q",
  tiktokLabel: "@padscha4",
};
